### ISSUE TITLE
Store developer profiles in git repo.

### ISSUE THREAD

**Issue by acedrew** [chadev/Chadev-issues#5]
I am proposing the following solution:
Subfolder in the root directory "profiles", inside will be a YAML file "developers.yml" this will store the profile objects with all associated meta-data. 
Inside /profiles/ there will be a folder "images", you would commit the image you want to use for your profile here, then simply place the url in an "image" tag in the YAML file.

I'm happy to build this out if everyone likes it. 
I don't see it as exclusionary to require you to use GIT to add yourself, I see it as an education opportunity. I know I would be happy to work with anyone that was having trouble.

Let me know.

**Comment by vendion** [comment]
Yeah I was thinking about it this morning and I liked the idea.  As for images, why not just pull the users Gravatar that way it is the same image that they use for other sites anyways?  While we are at it because the developer information won't be directly tied to the users GitHub Profile, would we want to optionally allow linking to BitBucket, Gitorious, etc (of course it would be crazy to try to support all of them, just the major ones)?  Also would we want to add in KeyBase.io information (just an idea)?

My previous comment about using Git for dev listing wasn't mean to sound exclusionary, and if anyone has problems doesn't know how to use it I would also be happy to help.  It was mostly meant as a joke, and a very bad one at that.  With it being on GitHub it would be super easy for others to add their information and we could have directions on how to fork, edit the file, commit changes, and submit a pull request all within GitHub if need be.

**Comment by acedrew** [comment]
I think the idea would be to provide a list of profile-name:url pairs in the YAML file, some people may want to share a lot, some just a little. The ones that would show in the listing would be their name, and their github account (You have to have an account to make a PR) Then when you viewed their profile, whatever metadata they wanted would show. Obviously if they list their profile on a cam site, we won't accept the PR. :)

**Comment by vendion** [comment]
I was thinking doing something like [Bootstraps Thumbnail](http://getbootstrap.com/components/#thumbnails) and display their Gravatar/supplied profile picture, under that link to their GitHub profile (required) and any optional profile fields they want.  So for example my entry would look like this

``` YAML
vendion:
  - gravatar: http://en.gravatar.com/vendion.json
  - github: https://github.com/vendion
  - bitbucket: https://bitbucket.org/vendion
  - website: https://vendion.me
  - keybase: https://keybase.io/vendion
```

I mean if we are going to use YAML syntax, might as well use YAML :)

From there if we want to build out a full profile page on Chadev they we can add a `profile` section to the YAML.

**Comment by acedrew** [comment]
@kylegordy I'm responding to your comment on the other thread here. Let's not do it with markdown. Just use lorem ipsum and a blank image. I'll use what you do as a template, and then populate it using JS. From the structured data in the YAML file.

**Comment by vendion** [comment]
@kylegordy for placeholder images do you use anything like http://placehold.it?

**Comment by acedrew** [comment]
@vendion Let's let @kylegordy take some time to think through the layout and such, I'd rather that all come from him, so that it's consistent. My plan is to just work on the technical roadblocks for what he's trying to do. That way the front-end has a cohesive feel.

My plan was to use http://mustache.github.io/ (in JS, not in the jekyll build) to load the data and output the actual profiles. So I'll just take his placeholder HTML and put template tags in it.

**Comment by kylegordy** [comment]
@acedrew @vendion I'm confused as to why we need javascript at all if we have a YMAL file of all the devs… We can have Jekyll loop through that file and populate all the fields into markup. Plus this would make the site more accessible and lightweight. Is there something I'm missing here? Also, @vendion I've never used http://placehold.it before but is looks rad. Thanks!

**Comment by acedrew** [comment]
I just had that same revelation. I'm checking now whether we can use the github profile image without hitting a rate limit. 
We'll set it up as a separate post type, and actually use a separate file for each dev, that way we don't end up with a giant file that is unmanageable, which was the major shortcoming of the large YAML file.

`acedrew.md`

```
---
name: Andrew Rodgers
website: http://acedrew.com
twitter: http://twitter.com/acedrew
---
Blurb in MD, for future full profile support
```

**Comment by kylegordy** [comment]
@acedrew Awesome, thanks for digging into this further :+1:

**Comment by vendion** [comment]
True if Jekyll can just parse the YAML file, during the build process I am
assuming?, then it would probably be better to do it there. Honestly on my
part is was not knowing what all Jekyll is capable of, this is my first
time using it.  Then the only time we may really need JS is if we did end
up going with Gravatars for user images.

@kylegordy I figured that would be a bit more convenient than manually
throwing together a blank, just give it dimensions and everything and it
handles the rest.

@acedrew why would we have to worry about pulling images from GitHub?  Last
I knew they used [Gravatar](https://en.gravatar.com/) on the backend for
that, so we could pull directly from there.  Also a separate markdown/yaml
file for each dev works for me.

**Comment by vendion** [comment]
Also if we are going to make social media links part of the profiles, please lets keep them optional.  I don't want to have to resurrect my twitter account or have to sign up for Facebook :P

**Comment by acedrew** [comment]
I think they're all optional. Some people don't have their own site.

**Comment by vendion** [comment]
Yeah I was being a bit sarcastic about that.

**Comment by acedrew** [comment]
@kylegordy here is what we'll be using: http://jekyllrb.com/docs/collections/
This will allow the profile page to simply be `for profile in site.profiles` it does not look like jekyll paginator supports collections yet.

**Comment by acedrew** [comment]
@kylegordy what's the proper way to handle jekyll plugins with VCS? There is a liquid filter that will generate gravatar hashes from email addresses already written I'd like to use. Should I just put it in _plugins and commit? 
Do we need to do something like this?
http://indelible.io/blog/2013/07/14/jekyll-plugins-and-github-pages.html

**Comment by kylegordy** [comment]
@acedrew Thanks for getting the ball rolling on the devs page. I just pushed some more changes to it, check 'em out. It's by no means done, but it's closer than we were :wink:

**Comment by acedrew** [comment]
I think this is sufficiently down the field that any further discussion should warrant a new issue. Ready to close?

**Comment by kylegordy** [comment]
@acedrew Agreed, I'll close it :+1:
