### ISSUE TITLE
Qualifications for group listing

### ISSUE THREAD

**Issue by acedrew** [chadev/Chadev-issues#6]
Guys, as we try to put more organization around this community, I'm thinking that we leave the events list/calendar open to anything that seems relevant to developers. The groups page, I'm thinking, will be reserved for those groups which meet certain qualifications, one of which being adopting our Code of Conduct. While that may seem a bit totalitarian, I think it's important that we set an example for other groups in terms of openness and inclusion.

Thoughts?

**Comment by vendion** [comment]
I don't see a problem with requiring groups to accepting a code of conduct.

**Comment by keathley** [comment]
I'm 100% ok with this.  :+1:

For clarity I'm also ok with a group using a code of conduct that isn't specifically the one that we're using.  For instance if they already have a CoC or something like that.  So maybe just phrase it as "To be accepted on this page your group has to have an accepted CoC"?

**Comment by kylegordy** [comment]
I also don't see a problem with it. I really love the idea about us setting an example for other groups in terms of openness and inclusion. :thumbsup:

**Comment by vendion** [comment]
I agree with @spyc3r it shouldn't be limited only to ours, but should be limited to an approved CoC.  So for example to list either the Drupal user group or the Google Developer Group their CoC would need to be reviewed by two or more of us.  Now both groups are required to follow strict code of conducts set by their respective communities.

This would also give us the chance to borrow from other CoCs in case we overlooked something or have yet to have to deal with something they have.

**Comment by acedrew** [comment]
One way we could handle this is make them link to their CoC in their "group profile" PR, that way we can review it, and we could directly link it from their profile. Making the CoC a first class citizen.

**Comment by keathley** [comment]
That seems fine to me.

**Comment by vendion** [comment]
I was toying with having them submit such requests via a issue and either
they state if they are using ours or link to the CoC their group uses.  If
they opt to use the Chadev CoC do they still need to link to it?  Seems
kind of redundant.

**Comment by acedrew** [comment]
Yes, I think the profile should have a link to their CoC, regardless of where it's hosted. Flow being, "oh this seems like a cool meetup, let's see if their CoC backs up that these are cool people, here's the direct link to their CoC, OH JOY!!! This peoples is awesome!!!" 

That's what I meant about the CoC being a first class citizen.

**Comment by vendion** [comment]
Yeah that makes sense to do it that way.

**Comment by kylegordy** [comment]
Agreed, that makes sense to me :+1:

**Comment by wilwade** [comment]
I wonder if Meetup groups can/should/could link back to the ChaDev CoC? On Meetup I can create a page with the CoC like http://www.meetup.com/pdxpython/pages/Code_of_Conduct/ or we could have a page with a note that says that the group conforms to the ChaDev CoC version 1.2.

Either way ChaDev CoC changes should be versioned and archived.

**Comment by keathley** [comment]
@wilwade The ChaDev CoC is here currently:

https://github.com/chadev/chadev.github.io/blob/master/coc.md

I'm fine with linking back to our page.  I'm sure there's some way to facilitate that on meetup.

**Comment by vendion** [comment]
```
Either way ChaDev CoC changes should be versioned and archived.
```

Agreed, we should have a policy in place where if the CoC needs to be changed, the commit that makes the change should be very detailed about why the change was made.  May even be able to use [Git Notes](https://github.com/blog/707-git-notes-display).  Archiving is handled automatically, and if someone is having problems getting diffs of it, someone here would be more than accommodating to help them out.  

I agree with explicit versioning the CoC, calling the current one "Chadev Code of Conduct v1.0.0" , following [Semantic versioning](http://semver.org/).  Another thing we can do is when the CoC needs to be updated, just update and commit that and tag with a "CoC-vx.x.x" so we can easily find and pull up previous versions.

@wilwade Small nitpick, the Capitalization is "Chadev", see the [style guide](https://github.com/chadev/style-guide/blob/master/README.md#text).

**Comment by wilwade** [comment]
@vendion "Capitalization is "Chadev""
I am all for that sort of nitpick. To nitpick back, why then does the logo use a lowercase "c"?

**Comment by vendion** [comment]
Well because the "ch" ligature ch in chatype doesn't work with an uppercase "C".  That wasn't really a design decision more of a font face technical issue.  Feel free to continue this on IRC or the style-guide issue queue.

**Comment by vendion** [comment]
Closing this as I think all CoC related issues have been resolved.
