### ISSUE TITLE
OpenBadges

### ISSUE THREAD

**Issue by keathley** [chadev/Chadev-issues#7]
I wanted to open this up for discussion (since @acedrew mentioned it on IRC).  How can we get this going, how can we let the community drive it, how can we help display peoples badges, how does this fit into your overall community profile, etc.  I know that this is something that I would love to have for lunch but I wanted to see what others thought.

**Comment by vendion** [comment]
I missed what @acedrew can the IRC log get copied somewhere so we can know what was said?

**Comment by keathley** [comment]
10:40 PM acedrew: Badges. We could totally do OpenBadges, with stickers to accompany
10:40 PM keathley: YES
10:41 PM kylegordy: Sounds rad!

**Comment by juzten** [comment]
This sounds awesome! Two ways we can display peoples badges is on the Chadev presentation we talked about that I believe @kylegordy put together that shows the Chadev logo, upcoming events, etc.. we can put together a random list of names every week,  and the other way could be on the chadev site, possibly on their dev profile or a page that shows a list of random users and their badges like a tag cloud almost.

**Comment by vendion** [comment]
I would be game for having them on the site.  They should work well on the full dev profile.  I'm also interested in the sticker aspect of it though, cuz stickers!

**Comment by acedrew** [comment]
https://wiki.mozilla.org/Badges/Onboarding-Issuer Just for everyone's reference, tackling this would be a big win, as it can immediately be used across our community. CodeXx, library, etc.

**Comment by kylegordy** [comment]
I would love to design a set of badges for us :+1:

**Comment by keathley** [comment]
At the very least I would love some stickers to hand out for lightning talk speakers.  This might get pricey but it could be fun to do limited runs or some sort of sweet one time swag per lightning talk session

**Comment by acedrew** [comment]
If we work with someone local, and develop a die cut that's the same each time, with a different graphic or something, I think we could get limited runs for reasonable pricing.

**Comment by keathley** [comment]
That works for me.  The point is that I would really like to generate sweet graphics so that we can celebrate new people giving talks.  That's maybe a point that is getting lost.  All of this is to try to create a really welcoming and inviting atmosphere for new speakers.  The don't have to be one offs.  But I thought they might be fun.  Maybe this is a once a year thing?  Then we could go all out.  Might even make it a small weekend bar conf type thing?

Ok I'm scope creeping.  Y'all gotta keep me honest.  Lets start by getting a sticker together that can also be a badge.  

Actually based on input that we've had so far are badges even worth pursuing?  It seems like the implementation from Mozilla is a bit loose.

**Comment by vendion** [comment]
I think the badges are a great idea. While may not be as effective as
something physical like stickers to try get give people an incentive to
give at least one talk be it a lightning talk or not, I'm sure it will
still help.

Would be even cooler if we make a mentor badge to give to people to
mentor someone just starting out or pair with someone less skilled at a
hack night. Basically rewarding people for trying to better the community
it always good.

**Comment by acedrew** [comment]
This, a hundred times this. It's about acknowledging the work of those in
the community.
And making it easy for newbies to track their accomplishments.

Andrew Rodgers
The Enterprise Center
Technologist-in-Residence
256-508-7610

**Comment by keathley** [comment]
That's f-:bomb: brilliant :+1: 

Acknowledging people who are giving back to community is a huge plus.  I really like helping to congratulate mentors.  that's fantastic.

**Comment by juzten** [comment]
I agree that physical items such as stickers are more effective. Agreed with statements about the people giving back to the community should get something to be noticed.

**Comment by kylegordy** [comment]
@vendion dude you're amazing :+1: So is everyone down with this being a physical sticker? Or are we still exploring digital solutions? I'm down either way. I would love to start brainstorming the design of a set of badges. What should our first set of badges acknowledge?

**Comment by vendion** [comment]
I say yes to badges, but not for just giving talks, things like stickers, DO Credits, etc would have more of a draw than badges.  We should get together at some point and workout some things that would earn people badges for being involved and/or bettering the community, or themselves for those that are new to the development world.

Of course I wouldn't be against having a "Presenter" badge as well :smile:

**Comment by acedrew** [comment]
I want both!

**Comment by keathley** [comment]
Off the top of my head I would love badges for presenters, mentors, and contributing to one of the community projects.  I'm trying to think of others.

**Comment by vendion** [comment]
While we have stickers, thank you @kylegordy and @juzten for keep making this happen, is there still a desire for badges?

**Comment by juzten** [comment]
I don't think so, I feel we can close this and if someone wants to revisit it we can re-open it in the future..which I don't think will happen.

**Comment by vendion** [comment]
Sounds good to me, closing for now.
