### ISSUE TITLE
Job Board

### ISSUE THREAD

**Issue by acedrew** [chadev/Chadev-issues#8]
What are everyone's thoughts on this? It seems it's a real need, we have a lot of people interested in addressing our group about jobs, and we're working hard to keep the environment at the meetups insulated from those types. However, we need there to be some vector for that energy in our community.

Feature wishlist? 
Thoughts?
Why this is a terrible idea?
etc?

**Comment by keathley** [comment]
I'm really in favor of something like this.  It's easy enough for us to push people to it since they've been asking.  I also think it would be cool for devs to be able to add their profiles and say if they were looking for contract / full time work.

**Comment by acedrew** [comment]
So I think this is something that should also serve as a revenue stream to support events and such that benefit the dev Community as a whole.
I eventually want to be able to kickstart new meetups with our organization, and take the load off of people interested in starting one, to find initial sponsors, etc.

I also think it's important we promote our local startup scene, by letting them post jobs at no or low cost.
The way to do that is low or no cost for principles only. If your company on your paycheck, and the company on the paycheck for the position are not the same, you need to pony up some way.

**Comment by StrangeWill** [comment]
I think it would be a healthy channel for people who want to discuss job opportunities, and I know some people will be looking at our group hoping to make those kinds of connections (from both ends).

I imagine this would be more of a portal and we'd have to move away from just using a static site? Otherwise our feature list is "what do we print on our site".

Would be cool to put in a little bit about what you need, and to reach out to chadevs that are subscribed for job listings in the fields/languages they're interested in.

**Comment by acedrew** [comment]
It's definitely a dynamic problem. But it's also a great group project. I don't know for sure how it interacts with the site. Not really worried about anything tech at this point, let's talk about what the requirements actually are.

**Comment by StrangeWill** [comment]
I know CHUGALUG has people post on behalf of other job openings knowing people in the group are looking for work.

It would be a neat feature, but a path for abuse around a paid system.

**Comment by acedrew** [comment]
Yeah, it's tricky, and I have no idea how to manage it.

**Comment by acruikshank** [comment]
I think it's fine so long as new job posts come in through pull requests.

**Comment by juzten** [comment]
@kylegordy and I talked about some of this in the beginning. 

I think there should be a job board. It does need to be moderated, I think it would be best not to let people post the jobs but let them send a job post request to an email address with appropriate information then we put them on the site and we take them down every few weeks. We could notify the person to see if the position still needs to be filled and we can leave it up a little while longer. The pull request idea would be less work on our part which is always a plus :)

I lean both ways on having it be a revenue stream. I like that idea and I think that if a company really needed to fill a position then they would likely pay to have it posted or sponsor an event for Chadev. Cons of making it a paid thing... If I know of a job that I'm not affiliated with, that does leave me out for helping the community by sharing the job with other devs. Plus...make all the things free!!!

I agree with @keathley about having a page where devs can add their profile and say they are looking for full/part time work in such and such language etc... Again, Kyle and I talked about this before so I'm glad it's coming up again. I got the idea before from another site...ill post it if I can find it.

**Comment by StrangeWill** [comment]
The revenue stream is a bit difficult though: it needs to be worth putting the money towards chadev and not just towards some other more well-known job posting site.

**Comment by juzten** [comment]
Here's the [link](http://bixly.com/) about dev profiles looking for work

**Comment by seabre** [comment]
We could do a Google form with moderated data and pull in postings that way.

**Comment by juzten** [comment]
I like the Google form idea @seabre

**Comment by vendion** [comment]
Agreed using a Google form is a simple solution, also gives us more control
over the data and make note of when a position has been filled instead of
requiring them to make a second PR to remove the listing.

**Comment by kylegordy** [comment]
:+1: for the Google form idea from @seabre
